name: parsec
version: '146-2'
summary: Parsec game streaming client
description: |
  Remotely connect to a gaming pc for a low latency remote computing
  experience.

icon: gui/parsec.png
confinement: strict
grade: stable

apps:
  parsec:
    command: desktop-launch $SNAP/usr/bin/parsecd
    desktop: usr/share/applications/parsec.desktop
    plugs:
      - alsa
      - desktop
      - hidraw
      - home
      - network
      - network-bind
      - opengl
      - pulseaudio
      - raw-usb
      - screen-inhibit-control
      - unity7
      - wayland
      - x11

parts:
  parsec:
    source: https://s3.amazonaws.com/parsec-build/package/parsec-linux.deb
    plugin: dump
    after:
      - desktop-gtk2
    stage-packages:
      - libsm6
      - libsndio6.1
      # FIX: Intel hardware video decoding
      - va-driver-all
      # FIX: AMD/NVIDIA hardware video decoding
      - vdpau-va-driver
